{"uuid": "131c7513-0065-4f89-bcc6-81e20a1be6a6", "children": ["05801c4b-f620-45f3-8126-303302f8c95a"], "befores": [{"name": "inventory_page", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'https://www.saucedemo.com/' == 'https://www.saucedemo.com/inventory.html'\n  \n  - https://www.saucedemo.com/inventory.html\n  ?                           --------------\n  + https://www.saucedemo.com/\n", "trace": "  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\dhamyan\\PycharmProjects\\PythonProject\\PythonProject\\Automated-testing-project\\test\\test_inventory.py\", line 24, in inventory_page\n    assert login_page.driver.current_url == \"https://www.saucedemo.com/inventory.html\"\n"}, "start": 1759173819808, "stop": 1759173820029}], "start": 1759173819808, "stop": 1759173820035}